### ISSUE TITLE
Adding Custom Styling

### ISSUE THREAD

**Issue by jrg94** [wll8/markdown-to-file#1]
Thanks for putting this together! I use it to automate PDF generation in one of my repos. One thing that bugs me about the project that this repo depends on is their switch to the yellow/brown color for inline code. I would like to be able to provide my own stylesheet, but I can't seem to do it with the current CLI tool. It seems the `styles` setting requires a list, which I can't provide on the CLI. Instead, I get something that looks like this:

```
options: {
  pdf: true,
  outputDirectory: 'E:\\Projects\\teaching-portfolio\\renders\\cse2221',
  styles: 'E:\\Projects\\teaching-portfolio\\scripts\\markdown.css'
}
```

Where the styles value is a string instead of a list. No additional brackets seem to do the trick either. Any suggestions would be awesome!

**Comment by wll8** [comment]
Processed. Please try after updating.

![image](https://github.com/wll8/markdown-to-file/assets/28223260/77957980-5b7f-4e43-8422-d59372a8a40d)


see: https://github.com/wll8/markdown-to-file/commit/a74ddfa30ed1e108ccb31f9e8cab41344fbc6e68.

``` sh
npm i -g markdown-to-file@1.5.0

# Use commas to separate multiple items.
m2f file.md pdf styles=D:/a.css,D:/b.css
```

**Comment by jrg94** [comment]
Works exactly as expected! Thank you.
